version: '3.1'

services:
  oracle-db:
    image: oracle/database:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: 20022002
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql-Oracle/startup:/opt/oracle/scripts/startup
      - ./sql-Oracle/sql:/opt/oracle/scripts/other-scripts
      - ./sql-Oracle/execute-sql-scripts.sh:/opt/oracle/scripts/startup/execute-sql-scripts.sh
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "SELECT 1 FROM DUAL;"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    shm_size: 2gb
    restart: on-failure
    networks:
      - my-bridge-network

  spring-boot-app:
    build: ./Auth-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: jorju
      SPRING_DATASOURCE_PASSWORD: 20022002
    depends_on:
      - oracle-db
    networks:
      - my-bridge-network

volumes:
  oracle-data:

networks:
  my-bridge-network:
    driver: bridge
