DROP TABLE INCIDENCIAS CASCADE CONSTRAINTS;
DROP TABLE CAMARAS CASCADE CONSTRAINTS;
DROP TABLE FLUJOS CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_INCIDENCIAS;
DROP SEQUENCE SEQ_CAMARAS;
DROP SEQUENCE SEQ_FLUJOS;


CREATE TABLE USUARIOS (
    EMAIL VARCHAR2(250) PRIMARY KEY,
    CONTRASENA VARCHAR2(256),  -- Asumiendo que la contraseña está encriptada
    TOKEN VARCHAR2(512),       -- Tamaño del token JWT
    SN_ADMIN VARCHAR(1)        -- Indicador de si el usuario es administrador
);


CREATE TABLE INCIDENCIAS(
    ID NUMERIC PRIMARY KEY
    ,TIPO VARCHAR2(255)
    ,CAUSA VARCHAR2(255)
    ,COMIENZO DATE
    ,NVL_INCIDENCIA VARCHAR2(2)
    ,CARRETERA VARCHAR2(255)
    ,DIRECCION VARCHAR2(255)
    ,LATITUD VARCHAR2(25)
    ,LONGITUD VARCHAR2(25)
    ,USUARIO VARCHAR2(250)
    ,CONSTRAINT FK_USUARIO_IN FOREIGN KEY (USUARIO) REFERENCES USUARIOS(EMAIL)
);

CREATE TABLE CAMARAS(
    ID NUMERIC PRIMARY KEY
    ,NOMBRE VARCHAR2(255)
    ,URL VARCHAR2(255)
    ,LATITUD VARCHAR2(25)
    ,LONGITUD VARCHAR2(25)
    ,CARRETERA VARCHAR2(255)
    ,KILOMETRO NUMERIC
    ,IMAGEN CLOB
    ,USUARIO VARCHAR2(250)
    ,CONSTRAINT FK_USUARIO_CA FOREIGN KEY (USUARIO) REFERENCES USUARIOS(EMAIL)
);

CREATE TABLE FLUJOS(
    ID NUMERIC PRIMARY KEY
    ,FECHA DATE
    ,RANGO_TIEMPO NUMERIC
    ,MEDIA_VELOCIDAD NUMERIC
    ,TOTAL_VEHICULOS NUMERIC
    ,LATITUD VARCHAR2(25)
    ,LONGITUD VARCHAR2(25)
    ,USUARIO VARCHAR2(250)
    ,CONSTRAINT FK_USUARIO_FL FOREIGN KEY (USUARIO) REFERENCES USUARIOS(EMAIL)
);


CREATE SEQUENCE SEQ_INCIDENCIAS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER T_INCIDENCIAS
BEFORE INSERT ON INCIDENCIAS
FOR EACH ROW
BEGIN
  SELECT SEQ_INCIDENCIAS.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/
CREATE SEQUENCE SEQ_CAMARAS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER T_CAMARAS
BEFORE INSERT ON CAMARAS
FOR EACH ROW
BEGIN
  SELECT SEQ_CAMARAS.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/
CREATE SEQUENCE SEQ_FLUJOS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER T_FLUJOS
BEFORE INSERT ON FLUJOS
FOR EACH ROW
BEGIN
  SELECT SEQ_FLUJOS.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/
commit;
